version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./dockerVolumes/rabbitmq_data:/var/lib/rabbitmq
      - ./dockerVolumes/rabbitmq_log:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    volumes:
      - ./dockerVolumes/mailhog_data:/mailhog/data

  postgres:
    image: postgres:15.7
    restart: unless-stopped
    container_name: postgresql-15.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./dockerVolumes/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '5050:80'
    depends_on:
      - postgres
    volumes:
      - ./dockerVolumes/pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  rabbitmq_data:
  rabbitmq_log:
  pgadmin_data:
